version: '3.7'
services:
  server-dev:
    profiles:
      - "dev"
    build: ./server
    container_name: tour-guy-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules

  client-dev:
    depends_on:
      - server-dev
    profiles:
      - "dev"
    build: ./client
    container_name: tour-guy-client
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
      - /app/node_modules